name: Deploy
on:
  workflow_run:
    workflows: ["Build"]  
    types:
      - completed

env:
  ECR_REGISTRY: "123456789012.dkr.ecr.us-east-1.amazonaws.com"
  ECR_REPOSITORY: "my-ecr-repo"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout 
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5"

      - name: Terraform Initialization
        run: terraform init 

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "image_name=985539765873.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:${GITHUB_SHA}"
